### PR TITLE
Need lz4-c 1.9 support for TileDB Cloud

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

Follow up to #184 and #189

cc: @johnkerl, @ktsitsi

We need a libtiledb-sql conda binary that co-installs with lz4-c 1.9 (lz4-c uses run exports [`x.x`](https://github.com/conda-forge/lz4-c-feedstock/blob/1771aeaed9cf4d91619cee1e822416b03e429f54/recipe/meta.yaml#L33)). Not bumping the build number because we only need to upload a single linux-64 binary built against lz4-c 1.9. No other build pins have changed.

### CODE REVIEW

**Comment by jdblischak** [comment]
@conda-forge-admin, please restart ci

**Comment by jdblischak** [comment]
Shoot. tiledb-feedstock was also already migrated to lz4-c 1.10 in https://github.com/conda-forge/tiledb-feedstock/pull/388

**Comment by johnkerl** [comment]
[[sc-59686]](https://app.shortcut.com/tiledb-inc/story/59686/update-projects-to-tiledb-2-27)

**Comment by jdblischak** [comment]
Superseded by https://github.com/TileDB-Inc/libtiledb-sql-feedstock/pull/2

**Pull request closed without merging**
